

services:
  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: ml_vuelos
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work/notebooks
      - ./data:/home/jovyan/work/data
    environment:
      - JUPYTER_TOKEN=ml2026
      - SPARK_DRIVER_MEMORY=4g
      - SPARK_EXECUTOR_MEMORY=4g
    mem_limit: 10g
    mem_reservation: 6g
    command: start-notebook.sh --NotebookApp.token='ml2026'
